/*
 * This source file was generated by the Gradle 'init' task
 */
package de.simon_neutert.map_tile_metrics;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class PointTest {
    @Test
    void pointIsRecord() {
        Point point = new Point(1, 2);
        // asssert that point is a record
        assertTrue(point instanceof Point);
    }

    @Test
    void pointHasXAndY() {
        Point point1 = new Point(1, 2);
        assertEquals(1, point1.x());
        assertEquals(2, point1.y());
    }

    @Test
    void pointCannotBeNegativeAndThrows() {
        assertThrows(IllegalArgumentException.class, () -> {
            new Point(-1, 2);
        });
        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            new Point(1, -2);
        });

        String expectedMessage = "x and y must be positive";
        String actualMessage = exception.getMessage();

        assertEquals(expectedMessage, actualMessage);
    }
}
